import {StyleSheet, Dimensions} from 'react-native';

const {width} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8fafc',
  },
  header: {
    backgroundColor: '#5a67d8',
    paddingHorizontal: 20,
    paddingVertical: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    shadowColor: '#4c51bf',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
  },
  content: {
    flex: 1,
    padding: 20,
  },
  welcomeText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#1a202c',
    marginBottom: 24,
    textAlign: 'center',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#f0f4f8',
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#2d3748',
    marginBottom: 12,
    textAlign: 'center',
  },
  cardDescription: {
    fontSize: 15,
    color: '#4a5568',
    marginBottom: 20,
    lineHeight: 22,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  button: {
    backgroundColor: '#5a67d8',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    elevation: 2,
    flex: 1,
    margin: 6,
    shadowColor: '#4c51bf',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
  },
  buttonText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 14,
    textAlign: 'center',
  },
  eventCard: {
    backgroundColor: '#f7fafc',
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
  },
  eventTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4a5568',
    marginBottom: 4,
  },
  eventText: {
    fontSize: 14,
    color: '#2d3748',
  },
  sequenceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    marginVertical: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#f7fafc',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  sequenceItemContainer: {
    margin: 4,
  },
  sequenceItem: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginRight: 8,
    backgroundColor: '#ebf8ff',
    borderWidth: 1,
    borderColor: '#bee3f8',
  },
  sequenceItemText: {
    fontSize: 14,
    color: '#2b6cb0',
    fontWeight: '500',
  },
  sequenceUpItem: {
    backgroundColor: '#e6fffa',
    borderColor: '#b2f5ea',
  },
  sequenceUpItemText: {
    color: '#2c7a7b',
  },
  sequenceDownItem: {
    backgroundColor: '#fef5ff',
    borderColor: '#fed7e2',
  },
  sequenceDownItemText: {
    color: '#b83280',
  },
  sequenceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  sequenceTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4a5568',
  },
  clearButton: {
    padding: 6,
    borderRadius: 4,
    backgroundColor: '#e2e8f0',
  },
  clearButtonText: {
    fontSize: 12,
    color: '#4a5568',
    fontWeight: '500',
  },
  buttonsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  sequenceButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 4,
  },
  volumeUpButton: {
    backgroundColor: '#38a169',
  },
  volumeDownButton: {
    backgroundColor: '#e53e3e',
  },
  sequenceButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  infoContainer: {
    marginTop: 8,
    padding: 12,
    backgroundColor: '#ebf8ff',
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#4299e1',
  },
  infoText: {
    fontSize: 14,
    color: '#2c5282',
    marginBottom: 6,
    lineHeight: 20,
  },
  sequenceActions: {
    flexDirection: 'row',
  },
  saveButton: {
    padding: 6,
    borderRadius: 4,
    backgroundColor: '#5a67d8',
    marginRight: 8,
  },
  saveButtonText: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '500',
  },
  savedSequencesCard: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#f0f4f8',
  },
  savedSequenceItem: {
    backgroundColor: '#f7fafc',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
  },
  savedSequenceInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  savedSequenceName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2d3748',
  },
  savedSequenceDate: {
    fontSize: 12,
    color: '#718096',
  },
  savedSequenceButtons: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  miniSequenceButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
  },
  miniSequenceButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  savedSequenceActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 8,
    alignItems: 'center',
  },
  loadButton: {
    backgroundColor: '#3B82F6',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginRight: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  loadButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  deleteButton: {
    backgroundColor: '#FEF2F2',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FECACA',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  deleteButtonText: {
    color: '#DC2626',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 20,
  },
  emptyStateText: {
    fontSize: 15,
    color: '#718096',
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: 20,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
  },
  modalScrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2d3748',
    marginBottom: 15,
    textAlign: 'center',
  },
  modalSubtitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4a5568',
    marginTop: 15,
    marginBottom: 10,
    textAlign: 'center',
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 10,
    marginBottom: 15,
    backgroundColor: '#f7fafc',
  },
  textInputContainer: {
    width: '100%',
    marginBottom: 15,
  },
  messageInput: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 10,
    backgroundColor: '#f7fafc',
    height: 100,
    textAlignVertical: 'top',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  modalSaveButton: {
    backgroundColor: '#5a67d8',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    flex: 1,
    marginLeft: 5,
    alignItems: 'center',
  },
  modalCancelButton: {
    backgroundColor: '#e2e8f0',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    flex: 1,
    marginRight: 5,
    alignItems: 'center',
  },
  modalSaveButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 14,
  },
  modalCancelButtonText: {
    color: '#4a5568',
    fontWeight: '600',
    fontSize: 14,
  },
  comboButton: {
    padding: 6,
    borderRadius: 4,
    backgroundColor: '#4c51bf',
    marginRight: 8,
  },
  comboButtonText: {
    fontSize: 12,
    color: '#ffffff',
    fontWeight: '500',
  },
  targetContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  targetLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4a5568',
  },
  targetName: {
    fontSize: 14,
    color: '#2d3748',
    fontWeight: '500',
  },
  messageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    paddingHorizontal: 0,
  },
  messageLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4a5568',
    marginRight: 4,
  },
  messageText: {
    fontSize: 14,
    color: '#2d3748',
    fontWeight: '400',
    flex: 1,
    flexWrap: 'wrap',
  },
  friendsContainer: {
    marginTop: 16,
    marginBottom: 20,
  },
  friendsScrollContent: {
    paddingVertical: 8,
  },
  friendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f7fafc',
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  friendItemSelected: {
    backgroundColor: '#ebf8ff',
    borderColor: '#90cdf4',
  },
  friendItemText: {
    fontSize: 16,
    color: '#4a5568',
    flex: 1,
    marginLeft: 12,
  },
  friendItemTextSelected: {
    color: '#2b6cb0',
    fontWeight: '600',
  },
  checkCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkCircleSelected: {
    borderColor: '#4299e1',
    backgroundColor: '#4299e1',
  },
  checkIcon: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: 'bold',
  },
  noFriendsContainer: {
    padding: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noFriendsText: {
    fontSize: 14,
    color: '#4a5568',
    textAlign: 'center',
    marginBottom: 10,
  },
  refreshButton: {
    backgroundColor: '#5a67d8',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 8,
  },
  refreshButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '500',
  },
  sequenceScrollView: {
    maxWidth: '100%',
  },
  infoCard: {
    backgroundColor: '#ebf8ff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: '#4299e1',
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#2b6cb0',
    marginBottom: 8,
  },
  actionButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editButton: {
    backgroundColor: '#EFF6FF',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BFDBFE',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  editButtonText: {
    color: '#2563EB',
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  recordingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    backgroundColor: '#FEF3C7',
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#FCD34D',
  },
  recordingIndicatorText: {
    color: '#92400E',
    fontWeight: '600',
    marginLeft: 8,
  },
  recordingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#EF4444',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2d3748',
    marginTop: 8,
    marginBottom: 16,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
  },
  listItem: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    borderWidth: 1,
    borderColor: '#f0f4f8',
  },
  listItemTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: '#2d3748',
    marginBottom: 6,
  },
  listItemDate: {
    fontSize: 12,
    color: '#718096',
    marginBottom: 8,
  },
  sequencePreview: {
    marginBottom: 15,
    padding: 10,
    backgroundColor: '#f7fafc',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  previewTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4a5568',
  },
  previewButtons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  previewButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 6,
  },
  previewButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  lastButtonAdded: {
    borderWidth: 2,
    borderColor: '#fbd38d',
  },
  serviceControls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  startButton: {
    backgroundColor: '#38a169',
    marginRight: 5,
  },
  runningButton: {
    backgroundColor: '#68d391',
    marginRight: 5,
  },
  stopButton: {
    backgroundColor: '#e53e3e',
    marginLeft: 5,
  },
  disabledButton: {
    opacity: 0.5,
  },
  friendsList: {
    marginVertical: 10,
  },
  friendCheckbox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    paddingVertical: 5,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#a0aec0',
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxSelected: {
    backgroundColor: '#5a67d8',
    borderColor: '#5a67d8',
  },
  checkmark: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  friendName: {
    fontSize: 14,
    color: '#2d3748',
  },
  createCombinationButton: {
    backgroundColor: '#5a67d8',
    padding: 16,
    borderRadius: 12,
    marginVertical: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  createCombinationButtonText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '600',
  },
  emptySequenceText: {
    fontSize: 14,
    color: '#718096',
    textAlign: 'center',
    padding: 16,
  },
  loadingContainer: {
    position: 'absolute',
    zIndex: 20,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#5a67d8',
    marginTop: 10,
    fontSize: 16,
    fontWeight: 'bold',
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
  },
});

export {styles};
